name: 'Terraform Lint'

on:
  workflow_call:

permissions:
  contents: read

jobs:
  terraform-lint:
    name: 'TF Validate code'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory
    - name: Terraform Init
      run: terraform init -backend=false

    # Validate terraform files
    - name: Terraform Validate
      run: terraform validate

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Check Format
      run: terraform fmt -check -recursive
    
    ## TFLint installation and configuration
    - uses: actions/cache@v3
      name: TFLint - Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v3
      name: TFLint - Setup
      with:
        tflint_version: latest

    - name: TFLint - Show version
      run: tflint --version

    - name: TFLint - Initiate
      run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}

    - name: TFLint - Execute
      run: tflint -f compact
